config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show, :update, :create, :destroy]

     root to: "home#index"

  resources :stocks, only: [:index]
  resources :trades, only: [:index, :create]

  get '/transactions' => "home#transactions"

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :users
  has_many :trades, through: :users
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :recoverable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :trades
  has_many :stocks, through: :trades

  validates :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def transactions
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class Devise::SessionsController < ApplicationController

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks_hash = Hash.new(0)
    current_user.trades.each do |t|
      if @stocks_hash[Stock.find(t.stock_id)[:ticker_symbol]]
        @stocks_hash[Stock.find(t.stock_id)[:ticker_symbol]] += t.qty
      else
        @stocks_hash[Stock.find(t.stock_id)[:ticker_symbol]] = t.qty
      end
    end

    @stocks_array = Array.new
    @stocks_hash. each do |key, value|
      @stocks_array.push([key, value])
    end

    render json: @stocks_array
  end


end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  def index
    render json: current_user.trades
  end

  def create
    @stock = Stock.find_or_create_by(ticker_symbol: params[:ticker])

    if current_user.cash >= (params[:stockData][:current_price] * params[:qty].to_i)
      @trade = Trade.create(user_id: current_user.id, stock_id: @stock.id, transaction_price: params[:stockData][:current_price], qty: params[:qty], ticker: params[:ticker])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @cash = '%.2f' % current_user.cash
    render json: @cash
  end

  def update
    current_user.update(cash: params[:cash])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
 <% csrf_token = form_authenticity_token %>


<%= react_component("App", {current_user: current_user, token: csrf_token}) %>

app/views/home/transactions.html.erb
<%= react_component("TradesContainer") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StockPortfolioApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_pack_tag 'application' %>
</head>
<body>

  <% if current_user %>
    <div class="nav">
      Logged in as <strong><%= current_user.name %></strong>.
      <br>
      <%= button_to('Logout', destroy_user_session_path, :method => :delete, :class => 'logout')%>
      <p>
        <%=link_to "Portfolio", root_path %> |
        <%=link_to "Transactions", transactions_path %>
      </p>
    </div>
  <% end %>


  <%= yield %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>